import Head from "next/head";

// import Components
import Layout from "../../src/Components/layout/layout";
import RecipeSingleIntro from "../../src/Components/recipeSingle/recipeSingle";
import SingleRecipes from "../../src/Components/singleRecipes/singleRecipes";

export default function RecipeSingle() {
  return (
    <>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <RecipeSingleIntro/>
        <SingleRecipes/>
      </Layout>
    </>

  );
}
