import Head from "next/head";

// import Components
import Layout from "../src/Components/layout/layout";
import ProductIntro from "../src/Components/productIntro/productIntro";
import RecipeIntro from "../src/Components/recipeIntro/recipeIntro";
import Recipes from "../src/Components/recipes/recipes";

export default function Recipe() {
  return (
    <>
      <Head>
        <title>Recipe Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout bgPathLay="recipe">
        <RecipeIntro/>
        <Recipes/>
      </Layout>
    </>

  );
}
