import Head from "next/head";

// import Components
import Layout from "../src/Components/layout/layout";
import ProductIntro from "../src/Components/productIntro/productIntro";
import RecipeIntro from "../src/Components/recipeIntro/recipeIntro";

export default function Product() {
  return (
    <>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <RecipeIntro/>
      </Layout>
    </>

  );
}
